backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use common\models\LoginForm;

use common\models\AllUser;
use common\models\Industry;
use common\models\UserType;
use yii\heleprs\Url;


use common\models\Skill;
use common\models\Course;
use common\models\Position;
use common\models\Documents;
use common\models\Education;
use common\models\Experience;
use common\models\ContactUs;
use common\models\PostJob;
use common\models\CampusPost;
use common\models\JobCategory;
use common\models\JobRelatedSkill;
use common\models\NewsLetter;
use common\models\CompanyWallPost;
use common\models\User;
use yii\web\UploadedFile;
use common\models\PasswordForm;
use common\models\JobRelevant;

use yii\filters\AccessControl;
use common\components\AccessRule;
/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'ruleConfig' => [
                    'class' => AccessRule::className(),
                ],
                'rules' => [
                    [
                        'actions' => ['login'],
                        'allow' => true,
                    ],
                    [

                        'actions' => ['login','index', 'error','alljob','deletejob','allemployee','deleteemployee','allemployer','deleteemployer','newslettersubscriber','deletenews','topjob','logout','jobdetail','editlogo','changepassword','feedbackrecord'],
                        'allow' => true,
                        'roles' => ['Admin','CandiateList','CompanyList'],
                    ],
                    [

                        'actions' => ['login','index', 'error','logout','changepassword'],
                        'allow' => true,
                        'roles' => ['BlogLogin'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        if(Yii::$app->user->identity->type->TypeName=='BlogLogin')
        {
            $this->layout='bloglayout';
        }
       $firstday=date("Y-m-d", strtotime('monday this week'));   
        $lastday=date("Y-m-d", strtotime('sunday this week'));
        $firstday=date('Y-m-d',strtotime ( '-1 days' , strtotime ( $firstday ) ) );
        
        
        $day=array();$date=$firstday;
        for($i=0;$i<7;$i++)
        {
            $day[$i]=date('Y-m-d',strtotime($date . "+1 days"));
            $date=$day[$i];
        }
        
        $result=array();
        foreach($day as $dk=>$dval)
        {
            $userlist=AllUser::find()->select(['COUNT(CASE WHEN UserTypeId =2 THEN 1 ELSE NULL END) AS Candidate','COUNT(CASE WHEN UserTypeId =3 THEN 1 ELSE NULL END) AS Company','COUNT(CASE WHEN UserTypeId =4 THEN 1 ELSE NULL END) AS Campus','COUNT(CASE WHEN UserTypeId =5 THEN 1 ELSE NULL END) AS Team','DATE(OnDate) AS OnDate'])->where(['DATE(OnDate)'=>$dval])->asarray()->one();
            $result['candidate'][$dval]=($userlist['Candidate'])?$userlist['Candidate']:0;
            $result['company'][$dval]=($userlist['Company'])?$userlist['Company']:0;
            $result['campus'][$dval]=($userlist['Campus'])?$userlist['Campus']:0;
            $result['team'][$dval]=($userlist['Team'])?$userlist['Team']:0;
        }
        
        $jobpost=PostJob::find()->select(['COUNT(CASE WHEN PostFor ="Candidate" THEN 1 ELSE NULL END) AS Candidate','COUNT(CASE WHEN PostFor ="Both" THEN 1 ELSE NULL END) AS Botht','COUNT(CASE WHEN PostFor ="Team" THEN 1 ELSE NULL END) AS Team','COUNT(CASE WHEN PostFor ="Company" THEN 1 ELSE NULL END) AS Company'])->asArray()->one();
        
        $campuspost=CampusPost::find()->select(['Count(*) AS CampusPost'])->asArray()->one();
        
        $totalmember=AllUser::find()->count();
        $totaljob=PostJob::find()->count();
        $careerbugwallpost=CompanyWallPost::find()->count();
        
        $datee=date('Y-m-d');
        $datee1=date('Y-m-d',strtotime ( '-1 days' , strtotime ( $datee ) ) );
        $datee2=date('Y-m-d',strtotime ( '-1 days' , strtotime ( $datee1 ) ) );

        $todaysuser=AllUser::find()->where(['OnDate'=>$datee,'IsDelete'=>0])->all();
        $todaysuser1=AllUser::find()->where(['OnDate'=>$datee1,'IsDelete'=>0])->all();
        $todaysuser2=AllUser::find()->where(['OnDate'=>$datee2,'IsDelete'=>0])->all();
        
        return $this->render('home',['days'=>$day,'userlist'=>$result,'jobpost'=>$jobpost,'campuspost'=>$campuspost,'totalmember'=>$totalmember,'totaljob'=>$totaljob,'wallpost'=>$careerbugwallpost,'datee'=>$datee,'datee1'=>$datee1,'datee2'=>$datee2,'today'=>$todaysuser,'today1'=>$todaysuser1,'today2'=>$todaysuser2]);
    }

    /**
     * Login action.
     *
     * @return string
     */
    
    
    public function actionLogin()
    {
             
        $this->layout='login';
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        
    
/* print_r($_REQUEST);
die(); */ 
        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
    
    public function actionAlljob()
    {
        if(Yii::$app->user->identity->type->TypeName=='BlogLogin')
        {
            $this->layout='bloglayout';
        }
        $model = new PostJob();
		
		if(isset($_GET['userid']) && $_GET['userid'] > 0 && isset($_GET['status'])){
			
			$alljob = $model->find()->where(['EmployerId'=>$_GET['userid'], 'JobStatus'=>$_GET['status']])->orderBy(['OnDate'=>SORT_DESC])->all();
		
		}elseif(isset($_GET['userid']) && $_GET['userid'] > 0){
			
			$alljob = $model->find()->where(['EmployerId'=>$_GET['userid']])->orderBy(['OnDate'=>SORT_DESC])->all();
		
		}else{
			$alljob = $model->find()->where(['IsDelete'=>0,'JobStatus'=>0])->orderBy(['OnDate'=>SORT_DESC])->all();
		}
        return $this->render('alljob', [
                'model' => $alljob,
            ]);
    }
    
     public function actionJobdetail($id)
    {
        if(Yii::$app->user->identity->type->TypeName=='BlogLogin')
        {
            $this->layout='bloglayout';
        }
        $model = new PostJob();
        $onejob = $model->find()->where(['IsDelete'=>0,'JobStatus'=>0,'JobId'=>$id])->one();
        return $this->render('jobdetail', [
                'model' => $onejob,
            ]);
    }
    
    public function actionTopjob($id,$tpjob)
    {
        if(Yii::$app->user->identity->type->TypeName=='BlogLogin')
        {
            $this->layout='bloglayout';
        }
        $model = new PostJob();
        $job = $model->find()->where(['JobId'=>$id])->one();
        if($tpjob==1)
        {
            $tjb=0;
        }
        else{
            $tjb=1;
        }
        $job->TopJob=$tjb;
        $job->save();      
        echo json_encode(1);
    }
    
    public function actionDeletejob($id)
    {
        $model = new PostJob();
        $job = $model->find()->where(['JobId'=>$id])->one();
        $job->IsDelete=1;
        $job->JobStatus=1;
        $job->save();      
        return $this->redirect(['alljob']);
    }

    
    public function actionAllemployee()
    {
        if(Yii::$app->user->identity->type->TypeName=='BlogLogin')
        {
            $this->layout='bloglayout';
        }
        $model = new AllUser();
        $allemployee = $model->find()->where(['IsDelete'=>0,'UserTypeId'=>2])->orderBy(['Ondate'=>SORT_DESC])->all();
        
        return $this->render('allemployee', [
                'model' => $allemployee,
            ]);
    }
    
    public function actionDeleteemployee($id)
    {
        $model = new AllUser();
        $employee = $model->find()->where(['UserId'=>$id])->one();
        $employee->IsDelete=1;
        $employee->save();      
        return $this->redirect(['allemployee']);
    }
    
    public function actionAllemployer()
    {
        if(Yii::$app->user->identity->type->TypeName=='BlogLogin')
        {
            $this->layout='bloglayout';
        }
        $model = new AllUser();
        $allemployer = $model->find()->where(['IsDelete'=>0,'UserTypeId'=>3])->orderBy(['OnDate'=>SORT_DESC])->all();
        
        return $this->render('allemployer', [
                'model' => $allemployer,
            ]);
    }
    public function actionDeleteemployer($id)
    {
        $model = new AllUser();
        $employer = $model->find()->where(['UserId'=>$id])->one();
        $employer->IsDelete=1;
        $employer->save();   
        return $this->redirect(['allemployer']);
    }
    
    public function actionNewslettersubscriber()
    {
        if(Yii::$app->user->identity->type->TypeName=='BlogLogin')
        {
            $this->layout='bloglayout';
        }
        $news=new NewsLetter();
        $allnewsletter=$news->find()->where(['IsDelete'=>0])->orderBy(['OnDate'=>SORT_DESC])->all();
        return $this->render('newslettersubscriber',['allnews'=>$allnewsletter]);
    }
    
    public function actionDeletenews($id)
    {
        $news=new NewsLetter();
        $newsone=$news->find()->where(['NewsLetterId'=>$id])->one();

backend/views/site/allemployee.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel common\models\PositionSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'All Candidate';
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="panel panel-flat">
<div class="panel-body">
<div class="position-index">
<legend class="text-bold"> Candidate Details </legend>
   <table class="table table-striped table-bordered" style="width: 100%;">
			<thead>
				<tr>
				   <th><a href="#">#</a></th>
				   <th><a href="#">Date</a></th>
				   <th><a href="#">Name</a></th>
				   <th><a href="#">Type</a></th>
				   <th><a href="#">Email</a></th>
				   <th><a href="#">Ph No.</a></th>
				   <th><a href="#">Action</a></th>
				</tr>
			</thead>
			<tbody>
 
<?php $i=0; if($model){  foreach($model as $value){ $i++; ?>
			<tr>
			       <td><?=$i;?></td>
			       <td> <?=date("d-m-Y",strtotime($value->Ondate));?></td>
			       <td> <?=$value->Name;?></td>
                               <td>  <?=$value->EntryType;?></td>
                               <td><?=$value->Email;?></td>
                               <td><?=$value->MobileNo;?></td>
			       <td>
				<span class="glyphicon glyphicon-eye-open"></span>
				<a href="<?=Url::to(['site/deleteemployee','id'=>$value->UserId]);?>" title="Delete" aria-label="Delete" data-confirm="Are you sure you want to delete this candidate?" data-method="post" data-pjax="0">
				<span class="glyphicon glyphicon-trash"></span></a>
				</span>
				</a>
			       </td>
			</tr>
			</tr>
<?php }}else{ ?>
			<tr>
				<td colspan="9">No Results Found.</td>
			</tr>
   
<?php } ?>
   

			</tbody>
			</table> 
</div>
</div>
</div>

backend/views/site/allemployer.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel common\models\PositionSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'All Company';
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="panel panel-flat">
<div class="panel-body">
<div class="position-index">
<legend class="text-bold"> Company Details </legend>
   <table class="table table-striped table-bordered" style="width: 100%;">
			<thead>
				<tr>
				   <th><a href="#">#</a></th>
				   <th><a href="#">Date</a></th>
				   <th><a href="#">Company Name</a></th>
				   <th><a href="#">Type</a></th>
				   <th><a href="#">Email</a></th>
				   <th><a href="#">Contact No.</a></th>
				   <th><a href="#">Action</a></th>
				</tr>
			</thead>
			<tbody>
 
<?php $i=0; if($model){  foreach($model as $value){ $i++; ?>
			<tr>
			       <td><?=$i;?></td>
			       <td> <?=date("d-m-Y",strtotime($value->Ondate));?></td>
			       <td> <?=$value->Name;?></td>
                               <td>  <?=$value->EntryType;?></td>
                               <td><?=$value->Email;?></td>
                               <td><?=$value->MobileNo;?></td>
			       <td>
				<span class="glyphicon glyphicon-eye-open"></span>
				<a href="<?=Url::to(['site/deleteemployer','id'=>$value->UserId]);?>" title="Delete" aria-label="Delete" data-confirm="Are you sure you want to delete this company?" data-method="post" data-pjax="0">
				<span class="glyphicon glyphicon-trash"></span></a>
				</span>
				</a>
			       </td>
			</tr>
<?php }}else{ ?>
			<tr>
				<td colspan="9">No Results Found.</td>
			</tr>
   
<?php } ?>
   

			</tbody>
			</table> 
</div>
</div>
</div>

backend/views/site/alljob.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel common\models\PositionSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Job Opening';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="panel panel-flat">
<div class="panel-body">
<div class="position-index">
<legend class="text-bold"> Total Job Opening</legend>
<div style="width: 100%;float: left;overflow: auto;">
   <table class="table table-striped table-bordered">
			<thead>
				<tr>
				   <th><a href="#">#</a></th>
				   <th><a href="#">Date</a></th>
				   <th><a href="#">JobTitle</a></th>
				   <th><a href="#">CompanyName</a></th>
				   <th><a href="#">Email</a></th>
				   <th><a href="#">Ph No.</a></th>
				   <th><a href="#">Location</a></th>
				   <th><a href="#">Action</a></th>
				   <th><a href="#">Top Job</a></th>
				   <th><a href="#">Job Status</a></th>
				   <th><a href="#">Post For</a></th>
				</tr>
			</thead>
			<tbody>
 
<?php $i=0; if($model){ foreach($model as $value){ $i++; ?>
			<tr>
			       <td><?=$i;?></td>
			       <td> <?=date("d-m-Y",strtotime($value->OnDate));?></td>
			       <td>
						   <a href="<?=Url::to(['site/jobdetail','id'=>$value->JobId]);?>" style="cursor: pointer;" ><?=$value->JobTitle;?></a></td>
                   <td><?=$value->CompanyName;?></td>
                  <td><?=$value->Email;?></td>
                  <td><?=$value->Phone;?></td>
			       <td><?=$value->Location;?></td>
			       <td>
				<a href="<?=Url::to(['site/deletejob','id'=>$value->JobId]);?>" title="Delete" aria-label="Delete" data-confirm="Are you sure you want to delete this job?" data-method="post" data-pjax="0">
				<span class="glyphicon glyphicon-trash"></span></a>
			       </td>
				   <td>
						   <?php
						   //if($value->PostFor=='Candidate')
						   //{
						   ?>
						   <input type="checkbox" value="<?=$value->TopJob;?>" <?php if($value->TopJob==1) echo "checked='checked'";?> onclick="topjob(<?=$value->TopJob;?>,<?=$value->JobId;?>);"/>
						   <?php
						   //}
						   ?>
				   </td>
				   <td>
					  <?php
					  if($value->JobStatus==0)
					  {
					  ?>
					  <b style="color: green;">Open</b>
					  <?php
					  }
					  else
					  {
					  ?>
					  <b style="color: red;">Closed</b>
					  <?php
					  }
					  ?>
				   </td>
				   <td><?=$value->PostFor;?></td>
			</tr>
<?php }}else{ ?>
			<tr>
				<td colspan="9">No Results Found.</td>
			</tr>
   
<?php } ?>
			</tbody>
			</table>
</div>
</div>
</div>
</div>
<script type="text/javascript">
		 function topjob(topjob,jobid) {
            $.ajax({url:"<?= Url::toRoute(['site/topjob']);?>?id="+jobid+"&tpjob="+topjob,
				   success:function(results)
				   {
				         location.reload(); 
				   }
			});
         }
</script>

backend/views/site/changepassword.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Plan */

$this->title = 'Change Password';
$this->params['breadcrumbs'][] = ['label' => 'Change Password', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="panel panel-flat">
    <div class="panel-body">
<div class="plan-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="plan-form">
    <?php $form = ActiveForm::begin(); ?>

	<div class="form-group">
			<label class="control-label col-lg-2">Old Password</label>
			<div class="col-lg-10">
		     <?= $form->field($model,'oldpass',['inputOptions'=>[
            'placeholder'=>'Old Password'
        ]])->passwordInput()->label(false) ?>
			</div>
	</div>

	<div class="form-group">
		<label class="control-label col-lg-2 col-lgdate">New Password</label>
		<div class="col-lg-10">
     <?= $form->field($model,'newpass',['inputOptions'=>[
            'placeholder'=>'New Password'
        ]])->passwordInput()->label(false) ?>
        </div>
	</div>
    
    <div class="form-group">
		<label class="control-label col-lg-2 col-lgdate">Confirm Password</label>
		<div class="col-lg-10">
     <?= $form->field($model,'repeatnewpass',['inputOptions'=>[
            'placeholder'=>'New Password'
        ]])->passwordInput()->label(false) ?>
        </div>
	</div>

    <div class="form-group">
        <label class="control-label col-lg-2">&nbsp;</label>
        <div class="col-lg-10">
        <?= Html::submitButton('Set <i class="icon-arrow-right14 position-right"></i>', ['class' => 'btn btn-success']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

</div>
    </div>
</div>

backend/views/site/editlogo.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

$url='/backend/web';
/* @var $this yii\web\View */
/* @var $model common\models\JobCategory */

$this->title = 'Edit Logo';
//$this->params['breadcrumbs'][] = ['label' => 'Job Categories', 'url' => ['index']];
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="panel panel-flat">
    <div class="panel-body">
<div class="job-category-create">
<legend class="text-bold"><?= Html::encode($this->title) ?></legend>
<div class="job-category-form">
    <?php $form = ActiveForm::begin(); ?>
	
	<?php
		if($model->logo)
		{
	?>
	<div class="form-group">
		<label class="control-label col-lg-2"></label>
		<div class="col-lg-10">
            <img src="<?=$url.'/'.$model->logo->Doc;?>" style="width: 100px;" />
		</div>
	</div>
	<?php
		}
	?>
    <div class="form-group">
		<label class="control-label col-lg-2">Logo For Hiring companies Block</label>
		<div class="col-lg-10">
            <?= $form->field($model, 'HiringCompaniesLogoId')->fileInput(['accept' => "application/jpeg, application/png, application/jpg"])->label(false) ?>
		</div>
	</div>

	
    <div class="form-group">
        <label class="control-label col-lg-2">&nbsp;</label>
        <div class="col-lg-10">
        <?= Html::submitButton($model->isNewRecord ? 'Create <i class="icon-arrow-right14 position-right"></i>' : 'Update <i class="icon-arrow-right14 position-right"></i>', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

</div>
    </div>
</div>

backend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

backend/views/site/feedbackrecord.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel common\models\PositionSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Job Relevant feedback Record';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="panel panel-flat">
<div class="panel-body">
<div class="position-index">
<legend class="text-bold"> Job Relevant Feedback Record</legend>
   <table class="table table-striped table-bordered" style="width: 100%;">
			<thead>
				<tr>
				   <th><a href="#">#</a></th>
				   <th><a href="#">Date</a></th>
				   <th><a href="#">Email</a></th>
				   <th><a href="#">Feedback</a></th>
				</tr>
			</thead>
			<tbody>
 
<?php $i=0; if($allnews){ foreach($allnews as $value){ $i++; ?>
			<tr>
			       <td><?=$i;?></td>
			       <td> <?=date("d-m-Y",strtotime($value->OnDate));?></td>
			       <td> <?=$value->Email;?></td>
			       <td>
                        <?=$value->Type;?>
			       </td>
			</tr>
<?php }}else{ ?>
			<tr>
				<td colspan="9">No Results Found.</td>
			</tr>
   
<?php } ?>
			</tbody>
			</table> 
</div>
</div>
</div>

backend/views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'My Yii Application';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Congratulations!</h1>

        <p class="lead">You have successfully created your Yii-powered application.</p>

        <p><a class="btn btn-lg btn-success" href="http://www.yiiframework.com">Get started with Yii</a></p>
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/doc/">Yii Documentation &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/forum/">Yii Forum &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/extensions/">Yii Extensions &raquo;</a></p>
            </div>
        </div>

    </div>
</div>

backend/views/site/newslettersubscriber.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel common\models\PositionSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'News letter';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="panel panel-flat">
<div class="panel-body">
<div class="position-index">
<legend class="text-bold"> News Letter Subscriber</legend>
   <table class="table table-striped table-bordered" style="width: 100%;">
			<thead>
				<tr>
				   <th><a href="#">#</a></th>
				   <th><a href="#">Date</a></th>
				   <th><a href="#">Email</a></th>
				   <th><a href="#">Action</a></th>
				</tr>
			</thead>
			<tbody>
 
<?php $i=0; if($allnews){ foreach($allnews as $value){ $i++; ?>
			<tr>
			       <td><?=$i;?></td>
			       <td> <?=date("d-m-Y",strtotime($value->OnDate));?></td>
			       <td> <?=$value->Email;?></td>
			       <td>
				<a href="<?=Url::to(['site/deletenews','id'=>$value->NewsLetterId]);?>" title="Delete" aria-label="Delete" data-confirm="Are you sure you want to delete this email?" data-method="post" data-pjax="0">
				<span class="glyphicon glyphicon-trash"></span></a>
				</span>
				</a>
			       </td>
			</tr>
<?php }}else{ ?>
			<tr>
				<td colspan="9">No Results Found.</td>
			</tr>
   
<?php } ?>
			</tbody>
			</table> 
</div>
</div>
</div>